# Netlify configuration for staging deployments
# For production GitHub Pages, configure via Cloudflare proxy

[build]
  publish = "dist"
  command = "npm run build"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"

    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"

    # Enable XSS protection (legacy browsers)
    X-XSS-Protection = "1; mode=block"

    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Permissions policy (restrict browser features)
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

    # Strict Transport Security (HTTPS only)
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://www.google-analytics.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    """

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules (if needed)
[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301
